wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.12
    start_time: 1655871634
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 2
      - 5
epoch:
  desc: null
  value: 100
loss:
  desc: null
  value: mean_loss
lr:
  desc: null
  value: 0.001
metric:
  desc: null
  value: MSE
